### PR TITLE
86 disallow the declaration of empty interfaces

### LINKED ISSUE #86: Disallow the declaration of empty interfaces
Disallow the declaration of empty interfaces.

An empty interface is equivalent to its supertype. If the interface does not implement a supertype, then the interface is equivalent to an empty object ({}). In both cases it can be omitted.

**INCORRECT**

```
// an empty interface
interface Foo {}

// an interface with only one supertype (Bar === Foo)
interface Bar extends Foo {}

// an interface with an empty list of supertypes
interface Baz {}
```

**CORRECT**
```
// an interface with any number of members
interface Foo {
  name: string;
}

// same as above
interface Bar {
  age: number;
}

// an interface with more than one supertype
// in this case the interface can be used as a replacement of a union type.
interface Baz extends Foo, Bar {}
```

### PR DESCRIPTION
**Pull request by cheese-framework**
### Pull Request Checklist: 

- [x] Please make sure all jobs pass before requesting a review. 
- [x] Assign yourself to the PR
- [x] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
- [x] Label it as "needs-review"
- [x] Have you lint your code locally before submission?
- [ ] Did you write tests where appropiate?

### Related Issue?
closes #86

### CODE REVIEW

File: CommonServer/Types/DB/DeleteBy.ts [hunk 1]
```diff
@@ -1,5 +1,5 @@
-import BaseModel from 'Common/Models/BaseModel';
 import DeleteOneBy from './DeleteOneBy';
+import BaseModel from '../../../Common/Models/BaseModel';
```
Comment (simlarsen) [inline CommonServer/Types/DB/DeleteBy.ts:2]: Why change this?

File: CommonServer/Types/DB/UpdateBy.ts [hunk 2]
```diff
@@ -1,5 +1,5 @@
-import BaseModel from 'Common/Models/BaseModel';
+import BaseModel from '../../../Common/Models/BaseModel';
```
Comment (simlarsen) [inline CommonServer/Types/DB/UpdateBy.ts:1]: Why change this import?

File: CommonUI/src/PayloadTypes/ModalPayloadType.ts [hunk 3]
```diff
@@ -1,5 +1,5 @@
 import ActionPayload from '../Types/ActionPayload';
-import ObjectID from 'Common/Types/ObjectID';
+import ObjectID from '../../../Common/Types/ObjectID';
```
Comment (simlarsen) [inline CommonUI/src/PayloadTypes/ModalPayloadType.ts:2]: revert this import

File: CommonUI/src/Types/ActionPayload.ts [hunk 4]
```diff
@@ -1 +1,4 @@
-export default interface ActionPayload {}
+import ObjectID from '../../../Common/Types/ObjectID';
```
Comment (simlarsen) [inline CommonUI/src/Types/ActionPayload.ts:1]: '../../../Common/Types/ObjectID' -> 'Common/Types/ObjectID'

Since Common is defined in package.json we dont need to do '../../../Common/'

**Review by simlarsen — CHANGES_REQUESTED** [review]

File: CommonUI/src/Types/ActionPayload.ts (hunk 4 above)
Comment (cheese-framework) [reply CommonUI/src/Types/ActionPayload.ts:1]: Okay I'll change it. It was yelling at me so I thought it was a bug

**Review by simlarsen — APPROVED** [review]
